POST http://localhost:3333/users HTTP/1.1
Content-Type: application/json

{
     "name": "ssddsds",
     "email": "teste22w@gmail.com",
     "password": "ds"
}

###
DELETE http://localhost:3333/users/63b6baba88e76428f8d0c68d HTTP/1.1
Content-Type: application/json

